version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:1.0
    container_name: localvocal-server
    depends_on:
      - redis
    ports:
      - '8001:8001'
  redis:
    image: redis
    expose:
      - 6379
volumes:
  node_modules:
